version: '3.8'

services:
  php:
    container_name: kitchen_store_php
    build:
      context: ./docker/php
    depends_on:
     - kitchen_store_db
    environment:
      DATABASE_URL: "postgresql://vlad:2819@kitchen_store_db:5432/kitchen_store"
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app_network

  kitchen_store_db:
    container_name: kitchen_store_db
    image: postgres:15
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: 2819
      POSTGRES_DB: kitchen_store
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  nginx:
    container_name: kitchen_store_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
