version: '3.8'

services:
  php:
    container_name: kitchen_store_php
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app_network

  db:
    container_name: kitchen_store_db
    image: postgres:15
    environment:
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
      POSTGRES_DB: kitchen_store
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  nginx:
    container_name: kitchen_store_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app_network

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
  db_data:

networks:
  app_network:
